services:
  frontend:
    container_name: django
    env_file: ../secrets/secrets.txt
    build: .
    ports:
      - 80:8000
    # networks:
    #   - front-tier
    #   - back-tier

  backend:
    env_file: ../secrets/secrets.txt
    build:
      context: .
      dockerfile: Dockerfile.db
    restart: always
    volumes:
      - ./data/postgres/pgdata:/var/lib/postgresql/data/pgdata
      - ./codesolid_demo:/home/myuser
    # networks:
    #   - back-tier
    ports: 
      - 5432:5432
    # environment:
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_DB: ${POSTGRES_DB}
    #   PGDATA: ${PGDATA}



# networks:
#   # The presence of these objects is sufficient to define them
#   front-tier: {}
#   back-tier: {}

