services:
  frontend:
    container_name: django
    env_file: ../secrets/secrets.txt
    build: .
    ports:
      - 80:8000
  backend:
    env_file: ../secrets/secrets.txt
    image: postgres:11.15-bullseye
    restart: always
    volumes:
      - ./data/postgres/pgdata:/var/lib/postgresql/data/pgdata
      - ./codesolid_demo:/home/myuser
    ports: 
      - 5432:5432
